### ISSUE TITLE
crash on playing hypixel bedwars with the mods stuff on

### ISSUE THREAD

**Issue by Cuteistfox** [moehreag/AxolotlClient-branding#114]
it seems like `io.github.axolotlclient.modules.hypixel.bedwars.BedwarsGame.getSelf()` returns null

log

```
[12:06:38] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "io.github.axolotlclient.modules.hypixel.bedwars.BedwarsPlayer.isBed()" because the return value of "io.github.axolotlclient.modules.hypixel.bedwars.BedwarsGame.getSelf()" is null
	at net.minecraft.class_329.localvar$zgb000$axolotlclient$displayHardcoreHearts(class_329.java:3057) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_329.method_37298(class_329.java:946) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_329.method_1760(class_329.java:830) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_329.method_1753(class_329.java:214) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:926) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.21.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.21.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.21.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.21.2.jar:?]
[12:06:39] [Render thread/INFO]:
 Stopping worker threads
```

mods

> 3d skin layers
chat heads
betterf3
axolotil client
cosmetica
ferritecore
lithium
mod menue
no chat reports
QKL
QSL and QFAPI
indium plus sudium
wavey capes
replay mod

**Comment by moehreag** [comment]
Could you please attach the full crash log (f.e. uploaded to https://mclo.gs)? And are you using Hypixel's nick feature by any chance?

**Comment by Cuteistfox** [comment]
[mclo.gs/knqfQgO](https://mclo.gs/knqfQgO) (no crash report was made)

**Comment by Cuteistfox** [comment]
and what is the nick fature?

**Comment by moehreag** [comment]
> and what is the nick fature?

It's a feature mainly for content creators to nick themselves (to not get targeted)

**Comment by Cuteistfox** [comment]
i dont use the nick feature

**Comment by moehreag** [comment]
> i dont use the nick feature

I figured and unfortunately I have no idea what caused this error.

**Comment by Cuteistfox** [comment]
im cheking the codee for `io.github.axolotlclient.modules.hypixel.bedwars.BedwarsGame`

**Comment by Cuteistfox** [comment]
theres also deprecated arrays all over the dpendecias part of the quilt.mod.json
```
12:11:20] [main/WARN]: Warnings for quilt.mod.json at: '<mods>/AxolotlClient-3.0.5+1.20.1.jar!/META-INF/jars/networking-6.0.3+1.20.1.jar!/quilt.mod.json'
[12:11:20] [main/WARN]: - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:11:20] [main/WARN]: - Unnecessary dependency range 1.20.1 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.20.1, 2)), since it doesn't affect the result [1.20, 2)
[12:11:20] [main/WARN]: Warnings for quilt.mod.json at: '<mods>/AxolotlClient-3.0.5+1.20.1.jar!/META-INF/jars/AxolotlClient-config-2.1.13+1.20.1.jar!/META-INF/jars/qsl_base-6.0.3+1.20.1.jar!/quilt.mod.json'
[12:11:20] [main/WARN]: - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:11:20] [main/WARN]: - Unnecessary dependency range 1.20.1 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.20.1, 2)), since it doesn't affect the result [1.20, 2)
[12:11:20] [main/WARN]: Warnings for quilt.mod.json at: '<mods>/AxolotlClient-3.0.5+1.20.1.jar!/META-INF/jars/AxolotlClient-config-2.1.13+1.20.1.jar!/META-INF/jars/lifecycle_events-6.0.3+1.20.1.jar!/quilt.mod.json'
[12:11:20] [main/WARN]: - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:11:20] [main/WARN]: - Unnecessary dependency range 1.20.1 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.20.1, 2)), since it doesn't affect the result [1.20, 2)
[12:11:20] [main/WARN]: Warnings for quilt.mod.json at: '<mods>/AxolotlClient-3.0.5+1.20.1.jar!/META-INF/jars/AxolotlClient-config-2.1.13+1.20.1.jar!/META-INF/jars/resource_loader-6.0.3+1.20.1.jar!/quilt.mod.json'
[12:11:20] [main/WARN]: - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
```

**Comment by Cuteistfox** [comment]
but i doud thats causing the bug

**Comment by moehreag** [comment]
> theres also deprecated arrays all over the dpendecias part of the quilt.mod.json
> 
> ```
> 12:11:20] [main/WARN]: Warnings for quilt.mod.json at: '<mods>/AxolotlClient-3.0.5+1.20.1.jar!/META-INF/jars/networking-6.0.3+1.20.1.jar!/quilt.mod.json'
> [12:11:20] [main/WARN]: - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
> [12:11:20] [main/WARN]: - Unnecessary dependency range 1.20.1 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.20.1, 2)), since it doesn't affect the result [1.20, 2)
> [12:11:20] [main/WARN]: Warnings for quilt.mod.json at: '<mods>/AxolotlClient-3.0.5+1.20.1.jar!/META-INF/jars/AxolotlClient-config-2.1.13+1.20.1.jar!/META-INF/jars/qsl_base-6.0.3+1.20.1.jar!/quilt.mod.json'
> [12:11:20] [main/WARN]: - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
> [12:11:20] [main/WARN]: - Unnecessary dependency range 1.20.1 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.20.1, 2)), since it doesn't affect the result [1.20, 2)
> [12:11:20] [main/WARN]: Warnings for quilt.mod.json at: '<mods>/AxolotlClient-3.0.5+1.20.1.jar!/META-INF/jars/AxolotlClient-config-2.1.13+1.20.1.jar!/META-INF/jars/lifecycle_events-6.0.3+1.20.1.jar!/quilt.mod.json'
> [12:11:20] [main/WARN]: - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
> [12:11:20] [main/WARN]: - Unnecessary dependency range 1.20.1 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.20.1, 2)), since it doesn't affect the result [1.20, 2)
> [12:11:20] [main/WARN]: Warnings for quilt.mod.json at: '<mods>/AxolotlClient-3.0.5+1.20.1.jar!/META-INF/jars/AxolotlClient-config-2.1.13+1.20.1.jar!/META-INF/jars/resource_loader-6.0.3+1.20.1.jar!/quilt.mod.json'
> [12:11:20] [main/WARN]: - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
> ```

This is caused by the qsl modules (embedded in the mod, will be left out in the future) being old and still using this now deprecated format

**Comment by Cuteistfox** [comment]
and it seems like hypixels sending bad packets
```
[12:11:54] [Render thread/WARN]: Received packet for unknown team a818536d2b44: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team NPCListShow: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team |||||||||||||||: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a289-27a5b1b8: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a818-1f73a47e: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a309-1caf72fb: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a828-57a839e6: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a999-76d80d5f: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team qg61174o1o: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a828-238b2c3a: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a908-b2fb9fd: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a409490ea5b6: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a908163bf9aa: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a2691ed5b53b: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a6296385b82a: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_1: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team 053q1o43w6: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a239-7788c508: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a23931cee4f7: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a60966d6cb33: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a90816408351: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a679-79569b33: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a6794e8b797a: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a679-278d515b: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a818-5aed9749: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a808-7e9f192f: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_15: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a5697e536498: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_13: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_14: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_11: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a908203421f7: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_12: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team NPCListHide: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_10: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_9: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team a828-7c93305b: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_8: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_7: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_6: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_5: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_4: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_3: team action: REMOVE, player action: null
[12:11:54] [Render thread/WARN]: Received packet for unknown team team_2: team action: REMOVE, player action: null
```

**Comment by moehreag** [comment]
it always does that, the only thing you can do about that is ignore the logspam it causes

**Comment by Cuteistfox** [comment]
hypixel i dont use badlion!
```
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
[12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
```

why does hypixel always clutter my logs with stuff for badlion

**Comment by moehreag** [comment]
> hypixel i dont use badlion!
> 
> ```
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> [12:12:15] [Render thread/WARN]: Unknown custom packed identifier: badlion:timers
> ```
> 
> why does hypixel always clutter my logs with stuff for badlion

They seem to offer integration with one of badlion's modules and this is how it looks if you don't use it

**Comment by Cuteistfox** [comment]
it turns out theres a mod to dissable hypixel badlion logspam

**Comment by Cuteistfox** [comment]
what is `transformed-mod-minecraft`? (is it part of the QSL or what)

**Comment by moehreag** [comment]
it's minecraft's game jar, the "transformed-mod-" part is made by quilt loader and its TransformCache (for allowing a little faster startups etc)

**Comment by Cuteistfox** [comment]
why does quilt care so much about `io.github.axolotlclient.modules.hypixel.bedwars.BedwarsGame.getSelf()` not being null

**Comment by moehreag** [comment]
Quilt doesn't at all, it just appears in the stacktrace since it wraps the game

**Comment by moehreag** [comment]
You can definitely work around this possible bug by disabling hardcore hearts in the bedwars module, I'm not sure why this error happened in the first place.

**Comment by Cuteistfox** [comment]
i wish i could get a backtrace

**Comment by Cuteistfox** [comment]
i cant even find `io.github.axolotlclient.modules.hypixel.bedwars.BedwarsPlayer.isBed()`

**Comment by moehreag** [comment]
https://github.com/AxolotlClient/AxolotlClient-mod/blob/837fecc0bb6f1c34701dd108268ff44c015075ad/1.20/src/main/java/io/github/axolotlclient/modules/hypixel/bedwars/BedwarsPlayer.java#L41-L41

(it has a lombok gettter attached to it from the `@Data` annotation)

**Comment by Cuteistfox** [comment]
[it cccrashes even without hardcore hearts](https://mclo.gs/IXpmBV7)

**Comment by Cuteistfox** [comment]
im not great at using java BTW so im mainly debuging this as a learning exersise

**Comment by moehreag** [comment]
https://github.com/AxolotlClient/AxolotlClient-mod/blob/837fecc0bb6f1c34701dd108268ff44c015075ad/1.20/src/main/java/io/github/axolotlclient/modules/hypixel/bedwars/BedwarsGame.java#L100-L114

The inherent flaw likely is somewhere in here since the self player isn't set in both instances

**Comment by Cuteistfox** [comment]
useing not enoth crashes when this crashes somehow makes the mc screen go to the dirt backround without saying (back to playing"

**Comment by Cuteistfox** [comment]
now "io.github.axolotlclient.modules.hypixel.bedwars.BedwarsPlayer.getStats()" is cuasing th breaking [log](https://mclo.gs/PVY746k)

**Comment by Cuteistfox** [comment]
porlby due to my changed config

**Comment by Cuteistfox** [comment]
if u want to isolate variables dont hire me

**Comment by Cuteistfox** [comment]
java Cannot invoke "io.github.axolotlclient.modules.hypixel.bedwars.BedwarsPlayer.getStats()" because "this.me" is null

**Comment by moehreag** [comment]
Is this crash still reproducible with the latest version?
