### ISSUE TITLE
Error:  java.lang.NoClassDefFoundError: Could not initialize class io.github.axolotlclient.util.DiscordRPC

### ISSUE THREAD

**Issue by shaunsingh** [moehreag/AxolotlClient-branding#19]
Running 1.8.9 + legacyfabric + saltlib using polymc, running into the following error:
Mod was downloaded from modrinth, but the same issue occurs with the one from the `releases` page

```
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class io.github.axolotlclient.util.DiscordRPC
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.github.axolotlclient.util.DiscordRPC
	at net.minecraft.class_1600.handler$zbg000$stop(class_1600.java:2931)
	at net.minecraft.class_1600.method_2947(class_1600.java)
	at net.minecraft.class_1600.method_5580(class_1600.java:5513)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	... 11 more
```

**Comment by moehreag** [comment]
could you try with a build from the actions tab if the issue persists?

**Comment by shaunsingh** [comment]
Looks like it's fixed now, thank you!
