### ISSUE TITLE
Freezing when try to join servers

### ISSUE THREAD

**Issue by HowardZHY** [moehreag/AxolotlClient-branding#41]
I found this on game output console, how to disable this connect?
org.apache.http.conn.HttpHostConnectException: Connect to moehreag.duckdns.org:443 [moehreag.duckdns.org/195.128.102.114] failed: Connection timed out: connect
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at io.github.axolotlclient.NetworkHelper.setOnline(NetworkHelper.java:70)
        at net.minecraft.class_1600.handler$zbj000$login(class_1600.java:3445)
        at net.minecraft.class_1600.method_2930(class_1600.java:2006)
        at net.minecraft.class_1600.method_2929(class_1600.java:1956)
        at net.minecraft.class_1845.method_7580(class_1845.java:130)
        at net.minecraft.class_2025.method_7795(class_2025.java:76)
        at net.minecraft.class_2025.method_1831(class_2025.java:13)
        at net.minecraft.class_2570$1.run(class_2570.java:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.class_1723.method_10652(class_1723.java:44)
        at net.minecraft.class_1600.method_2916(class_1600.java:881)
        at net.minecraft.class_1600.method_5580(class_1600.java:7057)
        at net.minecraft.client.main.Main.main(Main.java:124)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
        at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
        at java.net.Socket.connect(Socket.java:606)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:239)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
        ... 32 more
[12:59:18] [Client thread/ERROR]: (AxolotlClient) Error while logging in!

**Comment by moehreag** [comment]
This is the request telling the server you are playing, which means that other people get fetch that information show a badge next to your name. (Option to disable pending). This  shouldn't time out tho. A fix could be to implement that in a non-blocking way as well.

**Comment by HowardZHY** [comment]
so I need to disable show badges?

**Comment by moehreag** [comment]
That won't do it since there's currently no option being checked before doing that, but indeed that would be good

**Comment by moehreag** [comment]
> so I need to disable show badges?

now (with the latest commit) this would work.

**Comment by HowardZHY** [comment]
I'm going to try

**Comment by moehreag** [comment]
thank you

**Comment by HowardZHY** [comment]
thank you too

**Comment by moehreag** [comment]
btw, in the chinese translations all keys are fully lowercase which is incorrect. Could you try to sort that out?

**Comment by HowardZHY** [comment]
> btw, in the chinese translations all keys are fully lowercase which is incorrect. Could you try to sort that out?

The unicode-transform software transforms all letters to lowercase. It's too confusing to figure out unicode things. I can't fix it

**Comment by moehreag** [comment]
it also works without transforming the characters into their unicode equivalents though, the other language files only look like this because python's json library does this and they went through <https://github.com/moehreag/lang-to-json>

**Comment by HowardZHY** [comment]
I use transform tools from some public toolbox websites; and I didn't use lang files



At 2022-11-17 01:27:16, "moehreag" ***@***.***> wrote:

it should work all fine without transforming the characters into their unicode equivalents though, the other language files only look like this because python's json library does this and they went through https://github.com/moehreag/lang-to-json

**Comment by moehreag** [comment]
> I use transform tools from some public toolbox websites; and I didn't use lang files At 2022-11-17 01:27:16, "moehreag" ***@***.***> wrote: it should work all fine without transforming the characters into their unicode equivalents though, the other language files only look like this because python's json library does this and they went through https://github.com/moehreag/lang-to-json — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

ok, but why do they need to be transformed in the first place? Minecraft doesn't need it, it already works with the unformatted file.
