### ISSUE TITLE
Mixin Confilict with Custom Skin Loader

### ISSUE THREAD

**Issue by HowardZHY** [moehreag/AxolotlClient-branding#64]
https://github.com/HowardZHY/CustomSkinLoader-LegacyFabric/blob/1.8.9-14.14/src/main/java/customskinloader/mixin/MixinGuiPlayerTabOverlay.java

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2308 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_371.<init>(class_371.java:101)
	at net.minecraft.class_1600.method_2921(class_1600.java:471)
	at net.minecraft.class_1600.method_5580(class_1600.java:310)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector axolotlclient$showPlayerHeads$1(Lnet/minecraft/class_1600;)Z in axolotlclient.mixins.json:PlayerListHudMixin from mod axolotlclient failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap AxolotlClient-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)

**Comment by moehreag** [comment]
you can probably fix this by adding a priority > 1000 to your mixin

**Comment by HowardZHY** [comment]
I think my priority is 1010

**Comment by moehreag** [comment]
Ok, I need to admit that the way this is currently handled on this side is not ideal, though there isn't any way to do it better from what I can see. You could keep the same functionality by having a mixin into ClientConnection.isEncrypted though, since you always return true in this case.

**Comment by HowardZHY** [comment]
maybe I should use reflect to disable this
